//! Opt-in native OpenSSH forwarding test. Only disposable loopback sshd instances
//! and fixture keys are used; no user SSH configuration or running agent changes.
use super::ssh_tests::{approve, item, key, save};
use super::*;
use crate::vault::{CallerIdentityCache, ssh_agent, transport};
use std::os::unix::fs::PermissionsExt;
use std::process::{Child, Command, Stdio};
use std::sync::atomic::{AtomicBool, Ordering};

struct Process(Child);
impl Drop for Process {
    fn drop(&mut self) {
        let _ = self.0.kill();
        let _ = self.0.wait();
    }
}
struct Stop<'a>(&'a AtomicBool);
impl Drop for Stop<'_> {
    fn drop(&mut self) {
        self.0.store(true, Ordering::Release);
    }
}

#[test]
#[allow(clippy::too_many_lines)]
fn ssh_openssh_forwarding_pins_both_hosts_and_requires_a_separate_grant() {
    let Some(sshd) = std::env::var_os("FACTORSEAL_TEST_SSHD") else {
        eprintln!("Set FACTORSEAL_TEST_SSHD to run loopback OpenSSH forwarding interoperability");
        return;
    };
    let now = transport::unix_time().unwrap();
    let (directory, service) = service(now, UnsealLeasePolicy::default());
    let root = directory.path();
    let user_key = key(10);
    save(&service, &item(&user_key), now);
    let public = root.join("user.pub");
    std::fs::write(&public, user_key.public_key().to_openssh().unwrap()).unwrap();
    let username = String::from_utf8(Command::new("id").arg("-un").output().unwrap().stdout)
        .unwrap()
        .trim()
        .to_owned();
    assert!(
        username
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || matches!(c, '_' | '-'))
    );
    let mut servers = Vec::new();
    let mut ports = Vec::new();
    for seed in [11, 12] {
        let reservation = std::net::TcpListener::bind(("127.0.0.1", 0)).unwrap();
        let port = reservation.local_addr().unwrap().port();
        let host = root.join(format!("host-{seed}"));
        std::fs::write(
            &host,
            key(seed)
                .to_openssh(ssh_key::LineEnding::LF)
                .unwrap()
                .as_bytes(),
        )
        .unwrap();
        std::fs::set_permissions(&host, std::fs::Permissions::from_mode(0o600)).unwrap();
        let config = root.join(format!("sshd-{seed}.conf"));
        std::fs::write(&config, format!("Port {port}\nListenAddress 127.0.0.1\nHostKey {}\nPidFile {}\nAuthorizedKeysFile {}\nStrictModes no\nUsePAM no\nPasswordAuthentication no\nKbdInteractiveAuthentication no\nPubkeyAuthentication yes\nPermitRootLogin yes\nAllowAgentForwarding yes\nAllowUsers {username}\nLogLevel ERROR\n", host.display(), root.join(format!("pid-{seed}")).display(), public.display())).unwrap();
        drop(reservation);
        let mut server = Process(
            Command::new(&sshd)
                .args(["-D", "-e", "-f"])
                .arg(&config)
                .stdin(Stdio::null())
                .stdout(Stdio::null())
                .stderr(Stdio::inherit())
                .spawn()
                .unwrap(),
        );
        let end = Instant::now() + Duration::from_secs(5);
        while std::net::TcpStream::connect(("127.0.0.1", port)).is_err() {
            assert!(
                server.0.try_wait().unwrap().is_none(),
                "temporary sshd failed to start"
            );
            assert!(Instant::now() < end, "temporary sshd did not listen");
            std::thread::sleep(Duration::from_millis(25));
        }
        servers.push(server);
        ports.push(port);
    }
    let socket = root.join("factorseal/forward.sock");
    let (listener, _guard) = transport::unix_socket::bind_listener(&socket).unwrap();
    let stopping = AtomicBool::new(false);
    let cache = CallerIdentityCache::default();
    std::thread::scope(|scope| {
        let _stop = Stop(&stopping);
        let server = scope.spawn(|| {
            ssh_agent::serve(&service, &listener, &stopping, &|stream| {
                #[cfg(target_os = "linux")]
                {
                    crate::vault::linux::caller_identity(stream, &cache)
                }
                #[cfg(target_os = "macos")]
                {
                    crate::vault::macos::caller_identity(stream, &cache)
                }
            })
        });
        // Paths are temporary names generated by tempfile; quote them for the remote shell.
        let quoted_public = public.to_string_lossy().replace('\'', "'\\''");
        let nested = format!(
            "ssh -F /dev/null -o BatchMode=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=ERROR -o IdentitiesOnly=yes -i '{quoted_public}' -p {} {username}@127.0.0.1 true",
            ports[1]
        );
        let mut client = Process(
            Command::new("ssh")
                .args([
                    "-F",
                    "/dev/null",
                    "-o",
                    "BatchMode=yes",
                    "-o",
                    "StrictHostKeyChecking=no",
                    "-o",
                    "UserKnownHostsFile=/dev/null",
                    "-o",
                    "LogLevel=ERROR",
                    "-o",
                    "IdentitiesOnly=yes",
                    "-i",
                ])
                .arg(&public)
                .arg("-A")
                .arg("-p")
                .arg(ports[0].to_string())
                .arg(format!("{username}@127.0.0.1"))
                .arg(nested)
                .env("SSH_AUTH_SOCK", &socket)
                .stdin(Stdio::null())
                .stdout(Stdio::null())
                .stderr(Stdio::inherit())
                .spawn()
                .unwrap(),
        );
        let end = Instant::now() + Duration::from_secs(30);
        let mut approved = Vec::new();
        loop {
            let now = transport::unix_time().unwrap();
            let permissions = service
                .state
                .lock_live(Instant::now())
                .unwrap()
                .list_permissions(now)
                .unwrap()
                .1;
            for permission in permissions
                .iter()
                .filter(|permission| matches!(permission.state, PermissionState::Pending { .. }))
            {
                let destination = permission
                    .ssh_destination
                    .as_ref()
                    .expect("OpenSSH must bind every auth destination");
                assert_eq!(destination.user, username);
                let expected: Vec<_> = [11, 12]
                    .into_iter()
                    .take(approved.len() + 1)
                    .map(|seed| key(seed).fingerprint(ssh_key::HashAlg::Sha256).to_string())
                    .collect();
                assert_eq!(destination.host_keys, expected);
                assert!(approved.len() < 2, "unexpected third authorization");
                approve(&directory, &service, &permission.id, now);
                approved.push(permission.id.clone());
            }
            if let Some(status) = client.0.try_wait().unwrap() {
                assert!(status.success(), "OpenSSH forwarding failed");
                assert_eq!(approved.len(), 2);
                break;
            }
            assert!(Instant::now() < end, "forwarded SSH did not complete");
            std::thread::sleep(Duration::from_millis(25));
        }
        stopping.store(true, Ordering::Release);
        server.join().unwrap().unwrap();
    });
}
