name: CI

on:
  push:
    branches: [main]
  pull_request:

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: read

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: cachix/install-nix-action@v31
      - uses: cachix/cachix-action@v16
        with:
          name: devenv
      - name: Install devenv
        run: nix profile add nixpkgs#devenv
      - name: Check formatting
        run: devenv shell -- cargo fmt --all -- --check
      - name: Run Clippy
        run: devenv shell -- cargo clippy --all-targets --all-features
      - name: Run tests
        run: devenv test
